In [1]:
import numpy as np
import pandas as pd


In [5]:
#1
arr1 = np.arange(1, 11).reshape(2, 5)
print(" 1:\n", arr1)

 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#2
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print(" 2:\n", extracted_elements)

 2:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [6]:
#3
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print(" 3:\n", fruit_series)


 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
#4
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 45, 28, 35, 40, 23, 31, 29],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("4:\n", df)

4:
       name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   45      M
4      Eve   28      F
5    Frank   35      M
6    Grace   40      F
7   Hannah   23      F
8      Ian   31      M
9     Jack   29      M


In [9]:
#5
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("5:\n", df)

5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   45      M  Programmer
4      Eve   28      F     Manager
5    Frank   35      M     Analyst
6    Grace   40      F  Programmer
7   Hannah   23      F     Manager
8      Ian   31      M     Analyst
9     Jack   29      M  Programmer


In [10]:
#6
age_filtered_df = df[df['age'] >= 30]
print("6:\n", age_filtered_df)

6:
     name  age gender  occupation
1    Bob   30      M     Manager
3  David   45      M  Programmer
5  Frank   35      M     Analyst
6  Grace   40      F  Programmer
8    Ian   31      M     Analyst


In [11]:
#7
csv_filename = "dataframe_output.csv"
df.to_csv(csv_filename, index=False)
df_read = pd.read_csv(csv_filename)
print("7:\n", df_read)


7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   45      M  Programmer
4      Eve   28      F     Manager
5    Frank   35      M     Analyst
6    Grace   40      F  Programmer
7   Hannah   23      F     Manager
8      Ian   31      M     Analyst
9     Jack   29      M  Programmer
